igorkamyshev/farfetched

.changeset/violet-cobras-watch.md
apps/website/docs/api/operators/retry.md
packages/core/src/retry/__tests__/retry.spec.ts
packages/core/src/retry/retry.ts

`fallback` in `retry`

---

apps/website/docs/.vitepress/config.js
apps/website/docs/statements/typescript.md

TS statement

---

.changeset/clean-rice-vanish.md
apps/website/docs/api/primitives/query.md
packages/core/src/query/__tests__/create_headless_query.spec.ts
packages/core/src/query/create_headless_query.ts
packages/core/src/query/type.ts

`reset` in Query

---

.changeset/small-clouds-sip.md
packages/core/src/errors/__test__/guards.type_spec.ts
packages/core/src/errors/guards.ts

Fix type definitions of error guards

---

.changeset/fresh-years-float.md
apps/website/docs/.vitepress/config.js
apps/website/docs/integrations/zod/api/zod-contract.md
apps/website/docs/integrations/zod/index.md
packages/zod/.babelrc
packages/zod/.eslintrc.json
packages/zod/README.md
packages/zod/index.ts
packages/zod/package.json
packages/zod/project.json
packages/zod/src/__tests__/contract.test.ts
packages/zod/src/__tests__/contract.type_spec.ts
packages/zod/src/index.ts
packages/zod/src/zod_contract.ts
packages/zod/tsconfig.json
pnpm-lock.yaml
tsconfig.base.json
workspace.json

Add a complementary package for `zod` contracts

---

apps/website/docs/api/primitives/contract.md
apps/website/docs/api/primitives/mutation.md
apps/website/docs/api/primitives/query.md

Fixed links to source code on primitive pages

Fix links on primitives pages

---

.changeset/dry-zoos-bathe.md
packages/runtypes/src/__tests__/contract.test.ts
packages/runtypes/src/runtype_contract.ts

Runtypes more reach errors

---

.changeset/nine-spies-tickle.md
.changeset/plenty-dots-dance.md
.changeset/rich-points-shop.md
.changeset/rude-seahorses-flash.md
apps/website/docs/api/factories/create_json_query.md
apps/website/docs/api/factories/create_query.md
apps/website/docs/api/operators/retry.md
apps/website/docs/api/primitives/query.md
packages/core/src/query/__tests__/create_json_query.initial_data.type_spec.ts
packages/core/src/query/__tests__/create_json_query.spec.ts
packages/core/src/query/__tests__/create_query.spec.ts
packages/core/src/query/__tests__/create_query.type_spec.ts
packages/core/src/query/create_headless_query.ts
packages/core/src/query/create_json_query.ts
packages/core/src/query/create_query.ts
packages/core/src/query/type.ts
packages/core/src/retry/retry.ts

Initial value for Query

---

.changeset/short-meals-work.md
package.json
packages/core/src/query/__tests__/create_headless_query.serialize.spec.ts
packages/core/src/query/create_headless_query.ts
packages/core/src/query/type.ts
pnpm-lock.yaml

Serizlization

---

apps/website/docs/.vitepress/config.js
apps/website/docs/recipes/vite.md
apps/website/docs/shared/sids_plugins.md

Recipe: Vite

---

.changeset/calm-humans-sort.md
.changeset/loud-plums-shake.md
.changeset/tricky-boats-sin.md
apps/website/docs/api/ui/react.md
apps/website/docs/api/ui/solid.md
apps/website/docs/releases/0-5.md
apps/website/docs/tutorial/basic_query.md
packages/core/src/mutation/create_headless_mutation.ts
packages/core/src/mutation/type.ts
packages/core/src/query/create_headless_query.ts
packages/core/src/query/type.ts
packages/react/src/use_mutation.ts
packages/react/src/use_query.ts
packages/solid/src/use_mutation.ts

Support `@@unitShape` protocol of Effector

---

.changeset/smooth-turtles-brush.md
packages/core/src/__tests__/invalidate_cache_on_update.test.ts
packages/core/src/cache/key/key.ts
packages/core/src/update/update.ts
packages/test-utils/src/watch_query.ts

Invalidate `cache` after `update`

---

.changeset/dry-nails-explain.md
package.json
packages/solid/package.json
packages/solid/src/__tests__/create_query_resource.test.tsx
packages/solid/src/create_query_resource.ts
pnpm-lock.yaml

Re-trigger resource after `update` a _Query_

---

.changeset/blue-badgers-count.md
packages/core/src/contract/apply_contract.ts
packages/core/src/errors/create_error.ts
packages/core/src/errors/type.ts
packages/core/src/fetch/api.ts
packages/core/src/mutation/__tests__/create_headless_mutation.test.ts
packages/core/src/mutation/__tests__/create_json_mutation.test.ts
packages/core/src/mutation/__tests__/create_mutation.test.ts
packages/core/src/query/__tests__/create_headless_query.test.ts
packages/core/src/query/__tests__/create_headless_query.validate.test.ts
packages/core/src/remote_operation/create_remote_operation.ts

It's really convenient to have a response if data validation failed. This PR adds a response field in invalid data error

Add a response field in invalid data error

---

.changeset/spicy-rabbits-shop.md
apps/website/docs/api/primitives/mutation.md
apps/website/docs/api/primitives/query.md
packages/core/src/query/__tests__/create_headless_query.test.ts
packages/core/src/remote_operation/__test__/create_remote_operation.test.ts
packages/core/src/remote_operation/create_remote_operation.ts
packages/core/src/remote_operation/type.ts

Add `$idle` store which is similar to `$pending`, `$failed` or` $succeeded`. That store shows if the fetching started or not.

Add $idle store

---

.changeset/loud-lobsters-turn.md
apps/website/docs/.vitepress/config.js
apps/website/docs/api/contracts/typed-contracts.md
apps/website/docs/recipes/open_api.md
apps/website/docs/roadmap.md
apps/website/docs/tutorial/contracts.md
package.json
packages/typed-contracts/.babelrc
packages/typed-contracts/.eslintrc.json
packages/typed-contracts/CHANGELOG.md
packages/typed-contracts/README.md
packages/typed-contracts/index.ts
packages/typed-contracts/package.json
packages/typed-contracts/project.json
packages/typed-contracts/src/__tests__/contract.test-d.ts
packages/typed-contracts/src/__tests__/contract.test.ts
packages/typed-contracts/src/contract.ts
packages/typed-contracts/tsconfig.json
packages/typed-contracts/vite.config.ts
pnpm-lock.yaml
workspace.json

OpenAPI codegen

---

.changeset/kind-tips-grab.md
package.json
packages/solid/project.json
packages/solid/src/__tests__/create_query_resource.test.tsx
packages/solid/src/create_query_resource.ts
pnpm-lock.yaml

Support ErrorBoundary in SolidJS 1.5

---

.changeset/wicked-baboons-burn.md
packages/core/src/retry/__tests__/retry.query.test-d.ts
packages/core/src/retry/retry.ts

`ExecutionMeta` in `otherwise` of `retry`

---

.changeset/six-peas-grab.md
apps/website/docs/api/primitives/mutation.md
apps/website/docs/api/primitives/query.md
packages/core/src/mutation/__tests__/create_headless_mutation.test.ts
packages/core/src/mutation/create_headless_mutation.ts
packages/core/src/query/__tests__/create_headless_query.test.ts
packages/core/src/query/create_headless_query.ts
packages/core/src/remote_operation/__test__/create_remote_operation.test.ts
packages/core/src/remote_operation/create_remote_operation.ts
packages/core/src/remote_operation/type.ts

Add _Store_ `.$finished` to _Remote Operation_

---

packages/core/src/attach/__tests__/attach.query.test.ts

Test-case for sourced fields mess in attached operations

---

.changeset/twenty-cats-cheat.md
apps/website/docs/.vitepress/config.js
apps/website/docs/api/routers/atomic-router.md
packages/atomic-router/.babelrc
packages/atomic-router/.eslintrc.json
packages/atomic-router/CHANGELOG.md
packages/atomic-router/README.md
packages/atomic-router/index.ts
packages/atomic-router/package.json
packages/atomic-router/project.json
packages/atomic-router/src/__tests__/defer.test.ts
packages/atomic-router/src/__tests__/fresh.test-d.ts
packages/atomic-router/src/__tests__/fresh.test.ts
packages/atomic-router/src/__tests__/start.test-d.ts
packages/atomic-router/src/__tests__/start.test.ts
packages/atomic-router/src/chain.ptorocol.ts
packages/atomic-router/src/defer.ts
packages/atomic-router/src/fresh.ts
packages/atomic-router/src/start.ts
packages/atomic-router/tsconfig.json
packages/atomic-router/vite.config.ts
packages/core/project.json
packages/core/src/query/create_headless_query.ts
packages/core/src/query/type.ts
packages/core/src/remote_operation/type.ts
pnpm-lock.yaml

Atomic Router integration

---

.changeset/poor-ligers-kick.md
packages/core/src/libs/patronus/__test__/sourced.test.ts
packages/core/src/libs/patronus/sourced.ts
packages/core/src/mutation/create_json_mutation.ts
packages/core/src/query/create_json_query.ts
packages/core/src/remote_operation/create_remote_operation.ts
packages/core/src/retry/retry.ts
packages/core/src/trigger_api/keep_fresh.ts
packages/core/src/update/update.ts

Sourced fields internals re-work

---

.changeset/chilly-rocks-help.md
apps/website/docs/api/primitives/mutation.md
apps/website/docs/api/primitives/query.md
apps/website/docs/releases/0-10.md
packages/core/src/fetch/api.ts
packages/core/src/mutation/__tests__/create_json_mutation.test.ts
packages/core/src/mutation/create_headless_mutation.ts
packages/core/src/query/__tests__/create_json_query.fetching.concurrent.test.ts
packages/core/src/query/__tests__/query.aborted.test.ts
packages/core/src/query/create_headless_query.ts
packages/core/src/query/type.ts
packages/core/src/remote_operation/create_remote_operation.ts
packages/core/src/remote_operation/type.ts

Abort as separate status

---

packages/core/project.json
packages/core/src/remote_operation/__test__/create_remote_operation.test.ts
packages/core/src/remote_operation/create_remote_operation.ts
packages/core/src/remote_operation/type.ts
packages/core/src/remote_operation/with_call_object.ts

Moved from #363 due to bad rebase

Implement internal low-level call object API

---

apps/website/docs/recipes/open_api.md
apps/website/docs/recipes/vite.md
apps/website/docs/shared/sids_plugins.md

`pnpm install --dev` > `pnpm add --save-dev`
Previous discussion: https://github.com/igorkamyshev/farfetched/pull/368

Fix of the docs about `pnpm add --save-dev`

---

.changeset/wild-ears-kneel.md
packages/core/src/update/__tests__/update.test-d.ts
packages/core/src/update/__tests__/update.test.ts
packages/core/src/update/update.ts

`update` and _Query_ with initial data

---

.changeset/good-bees-smile.md
packages/core/src/query/__tests__/connect_query.test-d.ts
packages/core/src/query/connect_query.ts

fixes https://github.com/igorkamyshev/farfetched/issues/377

fix: Fix passing to connectQuery.target query with initialData

---

apps/website/docs/.vitepress/config.js
apps/website/docs/recipes/base_url.md
apps/website/docs/statements/no_globals.md

No globals

---

.changeset/fair-rabbits-sell.md
packages/core/src/libs/lohyphen/__tests__/is_equal.test.ts
packages/core/src/libs/lohyphen/is_equal.ts

Do not stop refreshing if source contains weird object

---

.changeset/metal-scissors-collect.md
packages/core/src/query/__tests__/create_json_query.fetching.concurrent.test.ts
packages/core/src/remote_operation/create_remote_operation.ts

Do not flick `.$status` during cancellation

---

.changeset/dull-paws-smoke.md
packages/core/src/fetch/api.ts
packages/core/src/mutation/create_json_mutation.ts
packages/core/src/query/create_json_query.ts

Support Cloudflare Workers runtime

---

apps/website/docs/.vitepress/config.js
apps/website/docs/api/contracts/valibot.md
apps/website/docs/tutorial/contracts.md
packages/valibot/README.md
packages/valibot/package.json
packages/valibot/src/__tests__/contract.test-d.ts
packages/valibot/src/__tests__/contract.test.ts
packages/valibot/src/index.ts
packages/valibot/src/valibot_contract.ts
packages/valibot/tsconfig.json
packages/valibot/tsconfig.lib.json
packages/valibot/tsconfig.spec.json
packages/valibot/vite.config.ts
pnpm-lock.yaml
tsconfig.base.json

[Valibot](https://valibot.dev/) is a new popular runtime validation library.
This PR adds contracts integration for Farfetched.

Add Valibot contract integration

---

.changeset/fuzzy-cooks-join.md
packages/core/package.json
packages/core/src/remote_operation/create_remote_operation.ts
packages/core/src/remote_operation/type.ts
packages/core/src/retry/__tests__/retry.test.ts
packages/core/src/retry/retry.ts

fix bug in `retry` with `contract`

---

.changeset/eleven-hounds-allow.md
.changeset/spotty-tigers-roll.md
packages/atomic-router/src/barrier.ts
packages/core/package.json
packages/core/src/concurrency/concurrency.ts
packages/core/src/remote_operation/__test__/create_remote_operation.test.ts
packages/core/src/remote_operation/create_remote_operation.ts
packages/core/src/remote_operation/type.ts

Abort all in-flight operations on `.reset`

---

.changeset/light-jars-destroy.md
packages/core/src/__tests__/relative_urls_in_jsdom.test.ts
packages/core/src/fetch/lib.ts

Fix support of relative urls in `createJsonQuery` and `createJsonMutation`

---

apps/website/changelog/cli.mjs
apps/website/docs/recipes/no_fetch.md

Correct the typo in `No Fetch in Mutation` section

 typo in `No Fetch in Mutation` section

---

.changeset/heavy-otters-hang.md
packages/core/src/fetch/__tests__/lib.test.ts
packages/core/src/fetch/lib.ts

Add fallback validation for Safari 14.0

---

apps/website/docs/api/factories/create_json_mutation.md
apps/website/docs/api/factories/create_json_query.md
apps/website/docs/tutorial/built_in_mutation_factories.md

Update createJsonQuery and createJsonMutation docs with link to declareParams #531

Update createJsonQuery and createJsonMutation docs

---

.changeset/old-onions-juggle.md
packages/core/src/index.ts

Export `ExecutionMeta`

---

.changeset/dry-comics-shop.md
packages/core/package.json
packages/core/src/fetch/__tests__/api.response.extract.test.ts
packages/core/src/fetch/api.ts
packages/core/src/fetch/json.ts
packages/core/src/libs/lohyphen/drain.ts
packages/core/src/libs/lohyphen/index.ts

Fix streaming in edge runtimes

---

.changeset/metal-dragons-teach.md
apps/showcase-solid-real-world-rick-morty/src/main.tsx
apps/website/docs/tutorial/devtools.md
packages/dev-tools/src/App.vue
packages/dev-tools/src/index.ts
packages/dev-tools/src/model/init.ts
packages/dev-tools/src/view-model/console.ts
packages/dev-tools/src/view-model/list.ts
packages/dev-tools/src/view-model/operation.ts

DevTools `logErrorsToConsole`
